filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.overwrite: true

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.labels.logging: "enabled"
          config:
            - type: log
              paths:
                - '/var/lib/docker/containers/${data.docker.container.id}/*.log'
              json.keys_under_root: false
              processors:
                - decode_json_fields:
                    fields: ['json.log']
                    target: app
                    process_array: true
                    max_depth: 8

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "http"
  username: elastic
  password: "${ELASTIC_PASSWORD}"

setup.kibana:
  host: "http://kibana:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  protocol: "http"